# Generated by Django 2.0.6 on 2018-06-23 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserProfile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_deleted', models.BooleanField(default=False)),
                ('last_msg_id', models.PositiveIntegerField(default=0)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='admin_chats', to='UserProfile.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='UserChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'Participating'), ('L', 'Left'), ('D', 'Deleted')], default='P', max_length=1)),
                ('muted', models.BooleanField(default=False)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_users', related_query_name='chat_users', to='Chats.Chat')),
                ('inviter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_users', related_query_name='invited_users', to='UserProfile.UserProfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', related_query_name='chats', to='UserProfile.UserProfile')),
            ],
        ),
    ]
