# Generated by Django 2.0.6 on 2018-06-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchat',
            name='status',
            field=models.CharField(choices=[('P', 'Participating'), ('L', 'Left'), ('D', 'Deleted')], default='P', max_length=1),
        ),
    ]
