# Generated by Django 2.0.6 on 2018-06-18 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserProfile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_msg_id', models.PositiveIntegerField(default=0)),
                ('deleted', models.BooleanField(default=False)),
                ('favourite', models.BooleanField(default=False)),
                ('user1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations1', related_query_name='conversations1', to='UserProfile.UserProfile')),
                ('user2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations2', related_query_name='conversations2', to='UserProfile.UserProfile')),
            ],
        ),
    ]
