# Generated by Django 2.0.6 on 2018-06-23 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserProfile', '0001_initial'),
        ('Chats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_msg_id', models.PositiveIntegerField(default=0)),
                ('last_msg_date', models.DateTimeField()),
                ('deleted', models.BooleanField(default=False)),
                ('favourite', models.BooleanField(default=False)),
                ('user1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations1', related_query_name='conversations1', to='UserProfile.UserProfile')),
                ('user2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations2', related_query_name='conversations2', to='UserProfile.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('S', 'Sent'), ('D', 'Delivered'), ('R', 'Read')], default='D', max_length=1)),
                ('text', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('parent_msg_id', models.PositiveIntegerField(default=0)),
                ('is_edited', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='own_messages', to='UserProfile.UserProfile')),
                ('chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='messages', to='Chats.Chat')),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='messages', to='Messages.Conversation')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='voted_for', to='Messages.Message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='voters', to='UserProfile.UserProfile')),
            ],
        ),
    ]
