# Generated by Django 2.0.6 on 2018-06-23 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='last_msg_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='last_msg_id',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
