# Generated by Django 2.0.6 on 2018-06-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('S', 'Sent'), ('D', 'Delivered'), ('R', 'Read')], default='D', max_length=1),
        ),
    ]
