# Generated by Django 2.0.6 on 2018-06-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messages', '0002_auto_20180623_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='last_msg_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
