# Generated by Django 2.0.6 on 2018-06-22 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', related_query_name='owner', to='UserProfile.UserProfile'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_users', related_query_name='contact_users', to='UserProfile.UserProfile'),
        ),
    ]
